version: "3"
services:
  es-machine-learning-app:
    build: spark-machine-learning
    image: es-machine-learning-app:latest
    container_name: es-machine-learning-app
    volumes:
    - ./output:/opt/output/
    environment:
      - ES_SPARK_MASTER=spark://spark-master:7077
      - ES_DATA_SOURCE=hdfs://hadoop:9000/data
      - ES_HEALTHCHECK_ENDPOINT=http://hadoop:50070/webhdfs/v1/data?op=GETFILESTATUS
      - ENABLE_INIT_DAEMON=false
  hadoop:
    build: ./hadoop
    hostname: hadoop
    image: hadoop
    container_name: hadoop
    ports:
      - "50070:50070"
      - "9000:9000"
    volumes:
      - ${ES_DATA_DIR}:/var/opt/extrasensory/data
  spark-master:
    image: bde2020/spark-master:3.0.1-hadoop3.2
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - ENABLE_INIT_DAEMON_STEP=false
  spark-worker-1:
    image: bde2020/spark-worker:3.0.1-hadoop3.2
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - ENABLE_INIT_DAEMON_STEP=false
  spark-worker-2:
    image: bde2020/spark-worker:3.0.1-hadoop3.2
    container_name: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - "8082:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - ENABLE_INIT_DAEMON_STEP=false
