version: "3"
services:
  es-ml-streaming-app:
    build: spark-ml-streaming
    image: es-ml-streaming-app:latest
    container_name: es-ml-streaming-app
    environment:
      - ES_SPARK_MASTER=spark://spark-master:7077
      - ES_DATA_SOURCE=hdfs://hadoop:9000/data
      - ES_KAFKA_SERVER=kafka-server
      - ES_KAFKA_PORT=9092
      - ES_TRAINED_MODEL_PATH=hdfs://hadoop:9000/model
      - ES_HEALTHCHECK_ENDPOINT=http://hadoop:50070/webhdfs/v1/data?op=GETFILESTATUS
      - ENABLE_INIT_DAEMON=false
  es-kafka-ml-producer-app:
    build: kafka-ml-producer
    image: es-kafka-ml-producer-app:latest
    container_name: es-kafka-ml-producer-app
    environment:
      - ES_HADOOP_SERVER=hdfs://hadoop:9000/
      - ES_FILE_PATH=/data/00EABED2-271D-49D8-B599-1D4A09240601.csv
      - ES_KAFKA_SERVER=http://kafka-server
      - ES_KAFKA_PORT=9092
      - ES_MILLISECONDS_BETWEEN_MESSAGES=200
      - ES_HEALTHCHECK_ENDPOINT=http://hadoop:50070/webhdfs/v1/data?op=GETFILESTATUS
      - ENABLE_INIT_DAEMON=false
  kafka-server:
    image: bitnami/kafka:2.5.0
    container_name: kafka-server
    ports:
      - "9092:9092"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-server:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-server:9092
    depends_on:
      - zookeeper-server
  zookeeper-server:
    image: bitnami/zookeeper:3.6.1
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  spark-master:
    image: bde2020/spark-master:3.0.1-hadoop3.2
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - ENABLE_INIT_DAEMON_STEP=false
  spark-worker-1:
    image: bde2020/spark-worker:3.0.1-hadoop3.2
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - ENABLE_INIT_DAEMON_STEP=false
  spark-worker-2:
    image: bde2020/spark-worker:3.0.1-hadoop3.2
    container_name: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - "8082:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - ENABLE_INIT_DAEMON_STEP=false
networks:
  default:
    external:
      name: project3-network